### PR TITLE
Refugee registration

### PR DESCRIPTION
**Pull request by frafajec**
- [x] Introduced form control (Formik + Yup)
- [x] Styling
- [x] Form submission

### CODE REVIEW

**Comment by frafajec** [comment]
@esukram I removed package.lock since I saw that yarn is also used.
Also you can test form if you want, just add api call to submit for now. Ill wrap things up tomorrow.

**Comment by tscherfler** [comment]
Thanks, @frafajec for removing the .lock file. It slipped in by accident with my PR.

**Comment by esukram** [comment]
We can switch to npm, as I heard there is no real benefit now to use yarn. Do you agree?

**Comment by frafajec** [comment]
Thats true, yarn is a bit more visual but npm does the same job. I personally dropped yarn simply because you need to install it additionally. You call gents.

**Comment by tscherfler** [comment]
I am fine with both. The only benefit of yarn I know is better package deduplication support. But I doubt(hope) we run into any issues with npm. I usually stick to npm anyway.

**Comment by frafajec** [comment]
@esukram form is done.
@tscherfler if you can take over the normal reg form I would appreciate it!

**Comment by tscherfler** [comment]
@frafajec awesome job. Sure, I will take over the provider form.

**Review by tscherfler — APPROVED** [review]

**Pull request merged**
